version: '3.9'

services:
  database:
    image: mariadb:10
    restart: unless-stopped
    ports:
      - 3307:3306
    env_file:
      - ./.env
  
  client:
    build: ./client/
    restart: unless-stopped
    networks:
      caddy:
        ipv4_address: 172.16.0.25
    labels:
      caddy: sexinfo.simon511000.fr
      caddy.reverse_proxy: "{{upstreams 3000}}"
  
  server:
    build: ./server/
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - database


networks:
  caddy:
    external: true